#pragma once
/*
#define	ARRAY_AM_SIZE	20   // DOMESTIC SIZE 
#define	ARRAY_FRN_SIZE	51	// FOREIGN SIZE
#define	ARRAY_OBJECT_SIZE	51	// FOREIGN SIZE

#define	SIZE_OF_CLT_NAME		30 + 1
#define	SIZE_OF_CLT_PASSWORD	30 + 1


typedef struct 
{
	char	szUserName[SIZE_OF_CLT_NAME];
	char	szPassword[SIZE_OF_CLT_PASSWORD];
	DWORD	dwIPAddress;
	UINT	uiPort;

	DWORD	dwIPAddress1;
	UINT	uiPort1;

}PIC_CLT_OPTIONS;



enum FEED_STATE{
	FEED_01_STARTING,
	FEED_02_STARTING,
	FEED_03_STARTING,

	FEED_01_RUNNING,
	FEED_02_RUNNING,
	FEED_03_RUNNING,

	FEED_01_STOPPING,
	FEED_02_STOPPING,
	FEED_03_STOPPING,

	FEED_01_STOPPED,
	FEED_02_STOPPED,
	FEED_03_STOPPED,

	FEED_RECORDING,
	FEED_PLAYBACK
};

*/
